web:
  build: .
  dockerfile: Dockerfile
  hostname: web
  container_name: qgis_striped
  environment:
    - PGUSER=docker
    - PGPASSWORD=docker
    - PGHOST=db
  ports:
    - "8000:8000"
  volumes:
    - ./striped:/striped
